# Generated by Django 4.0.3 on 2022-05-31 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallerywebsite_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
